//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileHis.Data.DataEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EZServerEntities : DbContext
    {
        public EZServerEntities()
            : base("name=EZServerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HISWORKLIST> HISWORKLIST { get; set; }
        public virtual DbSet<EZ_Image> EZ_Image { get; set; }
        public virtual DbSet<EZ_ImageDevice> EZ_ImageDevice { get; set; }
    }
}
