//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileHis.Data.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EZ_Image
    {
        public string IM_UIKey { get; set; }
        public string SE_UIKey { get; set; }
        public string SOPClassUID { get; set; }
        public int ImageNumber { get; set; }
        public string ImageDate { get; set; }
        public string ImageTime { get; set; }
        public string ObjectFile { get; set; }
        public string ObjectFileJPG { get; set; }
        public string IM_ImageDeviceID { get; set; }
        public string ImageStatus { get; set; }
        public Nullable<int> ImageWindow { get; set; }
        public Nullable<int> ImageLevel { get; set; }
        public string KeyImage { get; set; }
        public Nullable<int> DentalImageNum { get; set; }
        public string ProcessFlag { get; set; }
        public string BriefnessFlag { get; set; }
        public string IM_CDT { get; set; }
        public string IM_CU { get; set; }
        public string IM_MDT { get; set; }
        public string IM_MU { get; set; }
        public string HaveSendToRemote { get; set; }
        public string HaveMove { get; set; }
        public string HaveMoveDate { get; set; }
        public Nullable<int> FileSize { get; set; }
        public string FileReady { get; set; }
        public string CalcuteMaxMinFinally { get; set; }
        public string HasCompress { get; set; }
        public Nullable<int> ReferenceImageNumber { get; set; }
        public string FilmStatus { get; set; }
        public string CodeValue { get; set; }
        public string OperationWL { get; set; }
        public string SendStatus { get; set; }
    }
}
