//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileHis.Data.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISWORKLIST
    {
        public string HW_ACCESSIONNUMBER { get; set; }
        public string HW_MODALITY { get; set; }
        public string HW_SPSS_EXEDT { get; set; }
        public string HW_SPSS_EXETM { get; set; }
        public string HW_REFER_PHSICIAN { get; set; }
        public string HW_PERFORMING_PHSICIAN { get; set; }
        public string HW_REPORT_PHSICIAN { get; set; }
        public string HW_PATIENTID { get; set; }
        public string HW_PATIENTNAME { get; set; }
        public string HW_PATIENTOTHERID { get; set; }
        public string HW_PATIENTOTHERNAME { get; set; }
        public string HW_BIRTHDATE { get; set; }
        public string HW_BIRTHTIME { get; set; }
        public string HW_SEX { get; set; }
        public string HW_AGE { get; set; }
        public string HW_SIZE { get; set; }
        public string HW_WEIGHT { get; set; }
        public string HW_ETHNIC_GROUP { get; set; }
        public string HW_OCCUPATION { get; set; }
        public string HW_ADD_HISTORY { get; set; }
        public string HW_PATIENTCOMMENTS { get; set; }
        public string HW_STUDY_INSTANCE_UID { get; set; }
        public string HW_REFERSOPCLASSUID { get; set; }
        public string HW_REQ_SERVICE { get; set; }
        public string HW_REQ_P_DESC { get; set; }
        public string HW_REQ_P_CODESEQ { get; set; }
        public string HW_REQ_CONTRAST_AGENT { get; set; }
        public string HW_VISIT_STATUS_ID { get; set; }
        public string HW_P_I_R { get; set; }
        public string HW_S_STATION_AE { get; set; }
        public string HW_S_STATION_NAME { get; set; }
        public string HW_REQ_P_PRIORITY { get; set; }
        public string HW_REQ_P_LOCATION { get; set; }
        public string HW_SPS_DESC { get; set; }
        public string HW_REQ_P_ID { get; set; }
        public string HW_SOURCE { get; set; }
        public string HW_STATION { get; set; }
        public string HW_STNO { get; set; }
        public string HW_STATUS { get; set; }
        public string HW_EXEITEMNAME { get; set; }
        public string HW_EXEITEM { get; set; }
        public string HW_EXESUBITEM { get; set; }
        public string HW_EXEPART { get; set; }
        public string HW_CHGDT { get; set; }
        public string HW_CHGTM { get; set; }
        public string HW_ItemHasUse { get; set; }
        public string WL_CDT { get; set; }
        public string WL_CU { get; set; }
        public string WL_MDT { get; set; }
        public string WL_MU { get; set; }
        public string MPPS_ProcedureState { get; set; }
        public Nullable<int> MPPS_ProcedureCode { get; set; }
        public string HW_CARDNO { get; set; }
    }
}
