//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileHis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class worklist
    {
        public int WorklistID { get; set; }
        public string SpecificCharacterSet { get; set; }
        public string ScheduledProcedureStepSequence { get; set; }
        public string ScheduledStationAETitle { get; set; }
        public string ScheduledProcedureStepStartDate { get; set; }
        public System.DateTime ScheduledProcedureStepRealDate { get; set; }
        public string ScheduledProcedureStepStartTime { get; set; }
        public string ScheduledPerformingPhysiciansName { get; set; }
        public string ScheduledProcedureStepDescription { get; set; }
        public string ScheduledActionItemCodeSequence { get; set; }
        public string ScheduledProcedureStepID { get; set; }
        public string Modality { get; set; }
        public string RequestedProcedureID { get; set; }
        public string RequestedProcedureCodeSequence { get; set; }
        public string StudyInstanceUID { get; set; }
        public string ReferencedStudySequence { get; set; }
        public string ReferencedSOPClassUID { get; set; }
        public string ReferencedSOPInstanceUID { get; set; }
        public string RequestedProcedureDescription { get; set; }
        public string NamesOfIntendedRecipientsOfResults { get; set; }
        public string ReferringPhysiciansName { get; set; }
        public string ReferringPhysician { get; set; }
        public string RequestingService { get; set; }
        public string AccessionNumber { get; set; }
        public string OrderEnterersLocation { get; set; }
        public string ReferencedPatientSequence { get; set; }
        public string ReferencedSOPClassUID1 { get; set; }
        public string ReferencedSOPInstanceUID1 { get; set; }
        public int HospitalSNo { get; set; }
        public string InstitutionName { get; set; }
        public string PatientName { get; set; }
        public string PatientID { get; set; }
        public string OtherPatientID { get; set; }
        public string OtherPatientName { get; set; }
        public string PatientBirthDate { get; set; }
        public string PatientAge { get; set; }
        public string PatientSex { get; set; }
        public string EthnicGroup { get; set; }
        public string PatientComments { get; set; }
        public string AdditionalPatientHistory { get; set; }
        public string PregnancyStatus { get; set; }
        public string RadiationDoseSequence { get; set; }
        public string ExposureType { get; set; }
        public string KVP { get; set; }
        public string XRayTubeCurrent { get; set; }
        public string ExposureTime { get; set; }
        public string FilterType { get; set; }
        public string FilterMaterial { get; set; }
        public string StudyDescription { get; set; }
        public string StudyID { get; set; }
        public string DistributionCode { get; set; }
        public string NumberOfFilms { get; set; }
        public string CaseNo { get; set; }
        public string Flag { get; set; }
        public string LockFlag { get; set; }
        public System.DateTime LogDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string Status { get; set; }
    }
}
