//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileHis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class dicom_detail
    {
        public int DicomDetailNo { get; set; }
        public string SOPInstanceUID { get; set; }
        public Nullable<int> ImageDetailNo { get; set; }
        public Nullable<int> PatientMainNo { get; set; }
        public string PatientName { get; set; }
        public string PatientID { get; set; }
        public Nullable<System.DateTime> PatientBirthDate { get; set; }
        public string PatientSex { get; set; }
        public string OtherPatientIDs { get; set; }
        public string OtherPatientNames { get; set; }
        public string PatientComments { get; set; }
        public Nullable<int> RegionOfResidenceNo { get; set; }
        public string RegionOfResidence { get; set; }
        public Nullable<int> PatientPositionNo { get; set; }
        public string PatientPosition { get; set; }
        public Nullable<int> BranchOfServiceNo { get; set; }
        public string BranchOfService { get; set; }
        public Nullable<int> OrganizationNo { get; set; }
        public string OrganizationName { get; set; }
        public string OrganizationCategory { get; set; }
        public Nullable<int> InstitutionNo { get; set; }
        public string InstitutionName { get; set; }
        public Nullable<int> InstitutionDepartmentNo { get; set; }
        public string InstitutionDepartmentName { get; set; }
        public string AccessionNumber { get; set; }
        public Nullable<int> ModalityNo { get; set; }
        public string Modality { get; set; }
        public string BodyPartExamined { get; set; }
        public string XRayNo { get; set; }
        public string AdditionalPatientHistory { get; set; }
        public string CheckInNumber { get; set; }
        public string OperatorName { get; set; }
        public string AcquisitionDeviceProcessingDescription { get; set; }
        public Nullable<System.DateTime> StudyDate { get; set; }
        public Nullable<System.DateTime> SeriesDate { get; set; }
        public Nullable<System.DateTime> AcquisitionDate { get; set; }
        public Nullable<System.DateTime> ContentDate { get; set; }
        public Nullable<System.TimeSpan> StudyTime { get; set; }
        public Nullable<System.TimeSpan> SeriesTime { get; set; }
        public Nullable<System.TimeSpan> AcquisitionTime { get; set; }
        public Nullable<System.TimeSpan> ContentTime { get; set; }
        public Nullable<int> AcquisitionNumber { get; set; }
        public Nullable<int> InstanceNumber { get; set; }
        public Nullable<int> StudyDetailNo { get; set; }
        public string StudyInstanceUID { get; set; }
        public string StudyID { get; set; }
        public string StudyDescription { get; set; }
        public Nullable<int> SeriesDetailNo { get; set; }
        public string SeriesInstanceUID { get; set; }
        public string SeriesNumber { get; set; }
        public string ReferringPhysicianID { get; set; }
        public string ReferringPhysiciansName { get; set; }
        public Nullable<int> ReportNo { get; set; }
        public Nullable<System.DateTime> ReportCreateTime { get; set; }
        public string PhysicianApprovingInterpretation { get; set; }
        public string InterpretationDiagnosisDescription { get; set; }
        public Nullable<int> FilePathNo { get; set; }
        public string FileDisk { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
        public Nullable<int> FileSize { get; set; }
        public Nullable<int> BackupNo { get; set; }
        public string CheckStatus { get; set; }
        public string PrintFlag { get; set; }
        public string Status { get; set; }
    }
}
