//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileHis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class scheduled_action_item_code
    {
        public int ScheduledActionItemCodeNo { get; set; }
        public string CodeValue { get; set; }
        public string CodingSchemeDesignator { get; set; }
        public string CodingSchemeVersion { get; set; }
        public string CodeMeaning { get; set; }
        public Nullable<System.DateTime> ExamDate { get; set; }
        public string AccessionNumber { get; set; }
        public string PatientID { get; set; }
        public Nullable<int> OrganizationNo { get; set; }
        public Nullable<int> ExamDataNo { get; set; }
        public Nullable<System.DateTime> ExamRealDate { get; set; }
        public Nullable<System.TimeSpan> ExamRealTime { get; set; }
        public Nullable<int> ItemNo { get; set; }
        public string Status { get; set; }
    }
}
